# @package _global_

models:
  decoder:
    _target_: ${decoder_path}.UNet
    in_channels: [256, 512, 1024, 2048]  # ResNet50 채널 구성
    strides: [4, 8, 16, 32]              # Input layer scale
    inner_channels: 256                  # Hidden layer channel
    output_channels: 64                  # output layer channel
    bias: False