# @package _global_

defaults:
  - /preset/models/decoder/unet_resnet50
  - /preset/models/encoder/resnet50_backbone
  - /preset/models/head/db_head
  - /preset/models/loss/db_loss
  - _self_

models:
  # ResNet50 백본용 최적화 설정
  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.0008  # 더 큰 모델이므로 학습률 약간 감소
    weight_decay: 2e-4  # 더 강한 정규화
    betas: [0.9, 0.999]

  # 학습률 스케줄러
  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    T_max: 25  # 25 에포크 훈련
    eta_min: 1e-6