# @package _global_

dataset_base_path: "/data/ephemeral/home/OCR/data/datasets/"

datasets:
  train_dataset:
    _target_: ${dataset_path}.OCRDataset
    image_path: ${dataset_base_path}images/train
    annotation_path: ${dataset_base_path}jsons/train.json
    transform: ${transforms.train_transform}
  val_dataset:
    _target_: ${dataset_path}.OCRDataset
    image_path: ${dataset_base_path}images/val
    annotation_path: ${dataset_base_path}jsons/val.json
    transform: ${transforms.val_transform}
  test_dataset:
    _target_: ${dataset_path}.OCRDataset
    image_path: ${dataset_base_path}images/val
    annotation_path: ${dataset_base_path}jsons/val.json
    transform: ${transforms.test_transform}
  predict_dataset:
    _target_: ${dataset_path}.OCRDataset
    image_path: ${dataset_base_path}images/test
    annotation_path: null
    transform: ${transforms.test_transform}

transforms:
  train_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      # 크기 조정 (적당한 해상도)
      - _target_: albumentations.LongestMaxSize
        max_size: 832  # 640 -> 832로 증가 (메모리 절약)
        p: 1.0
      - _target_: albumentations.PadIfNeeded
        min_width: 832
        min_height: 832
        border_mode: 0
        p: 1.0

      # 강화된 데이터 증강
      - _target_: albumentations.HorizontalFlip
        p: 0.5
      - _target_: albumentations.Rotate
        limit: 5  # 작은 회전
        p: 0.3
      - _target_: albumentations.RandomBrightnessContrast
        brightness_limit: 0.2
        contrast_limit: 0.2
        p: 0.3
      - _target_: albumentations.HueSaturationValue
        hue_shift_limit: 10
        sat_shift_limit: 15
        val_shift_limit: 10
        p: 0.3
      - _target_: albumentations.GaussianBlur
        blur_limit: 3
        p: 0.1
      - _target_: albumentations.GaussNoise
        var_limit: 50
        p: 0.1

      # 정규화
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True

  val_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - _target_: albumentations.LongestMaxSize
        max_size: 832  # 검증도 동일한 크기
        p: 1.0
      - _target_: albumentations.PadIfNeeded
        min_width: 832
        min_height: 832
        border_mode: 0
        p: 1.0
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True

  test_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - _target_: albumentations.LongestMaxSize
        max_size: 832
        p: 1.0
      - _target_: albumentations.PadIfNeeded
        min_width: 832
        min_height: 832
        border_mode: 0
        p: 1.0
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True

  predict_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - _target_: albumentations.LongestMaxSize
        max_size: 832
        p: 1.0
      - _target_: albumentations.PadIfNeeded
        min_width: 832
        min_height: 832
        border_mode: 0
        p: 1.0
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    keypoint_params: null

dataloaders:
  train_dataloader:
    batch_size: 8  # 큰 이미지로 인해 배치 크기 줄임
    shuffle: True
    num_workers: 4
  val_dataloader:
    batch_size: 8
    shuffle: False
    num_workers: 4
  test_dataloader:
    batch_size: 8
    shuffle: False
    num_workers: 4
  predict_dataloader:
    batch_size: 1
    shuffle: False
    num_workers: 4

# 더 강한 후처리 파라미터
collate_fn:
  _target_: ${dataset_path}.DBCollateFN
  shrink_ratio: 0.6  # 0.4 -> 0.6로 증가
  thresh_min: 0.3
  thresh_max: 0.7