# @package _global_

defaults:
  - base
  - /preset/datasets/db_improved
  - /preset/models/model_resnet34
  - /preset/lightning_modules/base
  - _self_

# 실험 이름
exp_name: "resnet34_experiment"

# 훈련 설정
trainer:
  max_epochs: 25
  precision: 32  # BCE loss compatibility

# 배치 크기 (ResNet34는 ResNet18보다 큰 모델)
datasets:
  train:
    batch_size: 12  # 메모리 고려하여 약간 감소
  val:
    batch_size: 12
  test:
    batch_size: 12