# @package _global_

defaults:
  - base
  - /preset/datasets/db_improved
  - /preset/models/model_resnet50
  - /preset/lightning_modules/base
  - _self_

# 실험 이름
exp_name: "resnet50_experiment"

# 훈련 설정
trainer:
  max_epochs: 25
  precision: 32  # BCE loss compatibility

# 배치 크기 (ResNet50은 더 큰 모델)
datasets:
  train:
    batch_size: 1  # GPU 메모리 부족으로 최대한 감소
  val:
    batch_size: 1
  test:
    batch_size: 1
  image_size: [384, 384]  # 해상도 최대한 감소